### ISSUE TITLE
can't run the server

### ISSUE THREAD

**Issue by ekaplan-Zymergen** [feldroy/django-crash-course-live-class-001#8]
$ python manage.py runserver
Watching for file changes with StatReloader
INFO 2020-07-17 09:42:44,246 autoreload 26404 10592 Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 392, in check
    all_issues = self._run_checks(
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\checks\urls.py", 
line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\checks\urls.py", 
line 23, in check_resolver
    return check_method()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\functional.py", 
line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\functional.py", 
line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ekaplan\everycheese\config\urls.py", line 29, in <module>
    'cheeses/', include('everycheese.cheese.urls', namespace='cheeses'),
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'everycheese.cheese'
Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 599, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 584, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 299, in run
    self.run_loop()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 305, in run_loop
    next(ticker)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 345, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 361, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 260, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 141, in iter_modules_and_files
    resolved_path = path.resolve(strict=True).absolute()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\pathlib.py", line 1177, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen 
importlib._bootstrap>'

ekaplan@ZL-10846 MINGW64 ~/everycheese (master)
$ python manage.py runserver
Watching for file changes with StatReloader
INFO 2020-07-17 09:43:28,488 autoreload 28944 29632 Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 392, in check
    all_issues = self._run_checks(
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\checks\urls.py", 
line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\checks\urls.py", 
line 23, in check_resolver
    return check_method()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\functional.py", 
line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\functional.py", 
line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ekaplan\everycheese\config\urls.py", line 29, in <module>
    'cheeses/', include('everycheese.cheese.urls', namespace='cheeses'),
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'everycheese.cheese'
Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 599, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 584, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 299, in run
    self.run_loop()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 305, in run_loop
    next(ticker)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 345, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 361, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 260, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\site-packages\django\utils\autoreload.py", 
line 141, in iter_modules_and_files
    resolved_path = path.resolve(strict=True).absolute()
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\pathlib.py", line 1177, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\ekaplan\Miniconda3\envs\everycheese\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen 
importlib._bootstrap>'

**Comment by ekaplan-Zymergen** [comment]
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("everycheese.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'cheeses/', include('everycheese.cheese.urls', namespace='cheeses'),
    ),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

**Comment by ekaplan-Zymergen** [comment]
`from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("everycheese.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'cheeses/', include('everycheese.cheese.urls', namespace='cheeses'),
    ),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns
`

**Comment by sethbonnie** [comment]
In config/urls.py try `cheeses` instead of `cheese`  in `everycheese.cheese.urls`:
```py
path(
  'cheeses/', include('everycheese.cheeses.urls', namespace='cheeses'),
)
```
